import turtle
turtle.forward(100)
turtle.right(90)
turtle.fillcolor("red")
turtle.begin_fill()
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.end_fill()